tools headers: fix ARC64 support
By default __BITS_PER_LONG is set to 32 in
uapi/asm-generic/bitsperlong.h.

But given we're talking about 64-bit architecture here,
we need to override it with 64 from
arch/arc/include/uapi/asm/bitsperlong.h which we do here.

Well otherwise tools fail to build throwing:
---------------------------->8-------------------------
linux/tools/include/asm-generic/bitsperlong.h:14:2: error: #error Inconsistent word size. Check asm/bitsperlong.h

   14 | #error Inconsistent word size. Check asm/bitsperlong.h

      |  ^~~~~
---------------------------->8-------------------------

Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>